### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by hannorein** [dtamayo/spock#1]
Current syntax:

```
from spock import spockClassifier
model = spockClassifier()
model.predict(sim)
```

Maybe it is too early to worry about this, and we can definitely change later what the precise name of each class is, but it could make sense to define early what each object **is**.

1) Is _model_ used interchangeably with _classifier_? If so, let's use only one of the two. If not, the difference is not obvious to me.
2) Since `spockClassifier` is a python class, I should start with a capital letter. 
3) I would not repeat the name `spock` in the name of a class. It's redundant if it's already in the package name and a bit confusing. (Will the package `spock` offer many different `Classifier` classes? If so, then it should not include one called `spockClassifier`, something like `DefaultClassifier` would make it more intuitive.)

**Comment by dtamayo** [comment]
I agree with all of these. I did SpockClassifier in analogy to XGBClassifier, but I agree there shouldn't be any ambiguity...if there is ambiguity users can do spock.Classifier rather than from spock import Classifier. 

I think what we name things in the end will depend on whether we e.g. bundle Miles timescale regressor and this classifier (to save the repeated short integration) or not. At that point we can agree on the right name. 

Thanks!

**Comment by dtamayo** [comment]
Changed to StabilityClassifier, which is more descriptive
