### ISSUE TITLE
Mass instead of eccentricity? 

### ISSUE THREAD

**Issue by franpoz** [dtamayo/spock#12]
Hi, 
Is there any physical or computational restriction which prevents the user the usage of SPOCK to explore the stabilities in a range of masses instead of eccentricities? 

Thanks!

**Comment by dtamayo** [comment]
No, SPOCK can do that too. We just show eccentricities in the paper since that has a more dramatic effect on stability. One thing to keep in mind is that the training set only goes up to mass ratios (with the star) of 10^-4, or 2x Neptune around the Sun, which captures the  majority of known 3+ planet systems. I would bet that it extrapolates reasonably to higher masses, but we haven't tested it rigorously. If you're trying to run it on giant planet systems, it might be worth validating it against N-body. We would be interested in your results!

**Comment by franpoz** [comment]
Thanks!
