### ISSUE TITLE
period ratio of adjacent planets

### ISSUE THREAD

**Issue by franpoz** [dtamayo/spock#23]
Hello, 
I'm sorry, but this is not an issue but a question about the usage of SPOCK. 
I have been checking some papers that use SPOCK; for some, the period ratio of adjacent planets is >2. Maybe I misunderstood the original paper, but should not be limited the usage of SPOCK for these cases where the period ratio of adjacent planets is <2?

Thanks a lot in advance!

**Comment by dtamayo** [comment]
Hola Fran!

It's certainly risky to use a machine learning model outside the range of the training data, but in general I would expect using SPOCK on widely separated systems to be fairly reliable and give you high probabilities of stability (it does for example with the Solar System). The training set had adjacent pairs of planets separated by up to 30 Hill radii, which for the highest masses (~2M_Nep) is beyond a period ratio of 2. 

One place I would expect SPOCK to start to do badly is if you go both to higher separations AND to higher masses than the training set, where you can start getting instabilities due to secular chaos within 10^9 orbits. This is significantly outside SPOCK's training set and SPOCK's features are focused on shorter timescale MMRs rather than secular resonances. 

On a separate note, you had asked me a long time ago about tides in REBOUNDx. Tiger Lu recently implemented them and Hanno expanded REBOUND to be able to keep track of spins if this is ever useful to you: https://iopscience.iop.org/article/10.3847/1538-4357/acc06d/meta

**Comment by franpoz** [comment]
Thanks Dani for your answer! 

I will certainly check Tiger Lu's paper for the tide's evolution; that is a great implementation and sounds quite useful for many systems
