### ISSUE TITLE
2-planet system + 1 mass-less object

### ISSUE THREAD

**Issue by MilevaE** [dtamayo/spock#9]
This is not an issue, but a question about the concept and how `SPOCK` works. My apologies if this is not the place to ask this.

I  would like to evaluate the stability of a 2-planet system. However, as I understood from the documentation, `SPOCK` needs, at least, 3 planets. Could it make sense to include a far away particle with a very low mass to evaluate the stability of the 2 inner planets? In such a scenario,  the stability of the system should be driven by the two inner planets, isn't? 

something like: 

```
import rebound
from spock import FeatureClassifier
model = FeatureClassifier()

sim = rebound.Simulation()
M_ts = 332946 # Earth mass in solar mass 
sim.add(m=0.25)
sim.add(m=2.55/M_ts, a=0.02, e=0.30, l=0.5)
sim.add(m=3.53/M_ts, a=0.05, e=0.30, l=1.75)
sim.add(m=1e-4/M_ts, a=10.00, e=0.0, l=0.0) 
sim.move_to_com()
model.predict_stable(sim)
```

Thanks in advance!

**Comment by dtamayo** [comment]
Hi Mileva,

No, the stability is quite a bit different with two planets, and like you might expect, putting a distant low-mass planet reduces to the  two-planet case. Fortunately, the two-planet case is mostly understood analytically in various limits. The relevant paper is Hadden & Lithwick 2018.  We should implement their stability boundary in SPOCK because I'm sure others have the same confusion!

**Comment by MilevaE** [comment]
Thanks a lot Daniel!
